#
# RCBOT 2 config file
#
# enter bot commands to execute
#
#mp_timelimit 0
#mp_respawnwavetime 0
#tf_flag_caps_per_round 0
#
# bot_crouch needed for bots to crouch!!!
#
#sv_cheats 1
#bot_crouch 1
# uncomment to let bots change classes
#rcbot_change_classes 1
rcbot_defrate 0.1
rcbot_visrevs 8
